# Generated by Django 4.0.2 on 2022-02-11 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_nutrition_caffeine_mg_alter_nutrition_drink_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='drink',
            name='english_name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='drink',
            name='korean_name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='menu',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='size',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='size',
            name='size_fluid_ounce',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='size',
            name='size_ml',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
