# Generated by Django 4.0.2 on 2022-02-11 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_category_name_alter_drink_english_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='allergy',
            name='drink_set',
            field=models.ManyToManyField(through='products.Allergy_Drink', to='products.Drink'),
        ),
        migrations.RemoveField(
            model_name='allergy',
            name='name',
        ),
        migrations.AddField(
            model_name='allergy',
            name='name',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
