# Generated by Django 4.0.2 on 2022-02-11 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_allergy_drink_set_remove_allergy_name_allergy_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allergy',
            name='name',
            field=models.CharField(default='', max_length=40),
        ),
    ]
